Version: 0.1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "go-microservice"
        LoadBalancerInfo: 
          ContainerName: "go-microservice" 
          ContainerPort: 8080