trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build
    displayName: 'Build'

    jobs:

      - job: build
        displayName: 'Build Application'
        steps:

        - task: Docker@2
          inputs:
            containerRegistry: 'gcrServiceConnection'
            repository: 'gcp-cf-272812/go-microservice'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.SourceVersion)'

      - job: package
        displayName: "Helm Package"
        steps:

        - task: HelmDeploy@0
          displayName: 'Package helm chart'
          inputs:
            command: 'package'
            chartPath: './chart'
            destination: '$(Build.ArtifactStagingDirectory)'
            save: false

        - task: PublishBuildArtifacts@1
          displayName: 'Publish chart locally'
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: helm

  - stage: dev
    displayName: 'Development'

    jobs:

      - deployment: deploy
        displayName: 'Deploy Helm Chart'
        environment: dev.default
        variables:
          img_url: 'gcr.io/gcp-cf-272812/go-microservice:$(Build.SourceVersion)'

        strategy:
          runOnce:
            deploy:
              steps:

                - task: ExtractFiles@1
                  inputs:
                    archiveFilePatterns: $(Agent.BuildDirectory)/helm/go-microservice-0.1.0.tgz
                    cleanDestinationFolder: true
                    destinationFolder: '$(Agent.BuildDirectory)/helm/go-microservice-0.1.0'

                - task: HelmDeploy@0
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: 'dev-default-1589456418781'
                    namespace: default
                    command: 'upgrade'
                    valueFile: '$(Agent.BuildDirectory)/helm/go-microservice-0.1.0/go-microservice/$(Environment.Name).yaml'
                    overrideValues: blue.image=$(img_url),green.image=$(img_url)
                    chartType: 'FilePath'
                    chartPath: $(Agent.BuildDirectory)/helm/go-microservice-0.1.0.tgz
                    releaseName: 'go-microservice'
