trigger:

  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build
    displayName: 'Build'

    jobs:

      - job: build
        displayName: 'Build Application'
        steps:

        - task: Docker@2
          inputs:
            containerRegistry: 'gcrServiceConnection'
            repository: 'gcp-cf-272812/go-microservice'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.SourceVersion)'

      - job: package
        displayName: "Helm Package"
        steps:

        - task: HelmDeploy@0
          displayName: 'Package helm chart'
          inputs:
            command: 'package'
            chartPath: './chart'
            destination: '$(Build.ArtifactStagingDirectory)'
            save: false

        - task: PublishBuildArtifacts@1
          displayName: 'Publish chart locally'
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: helm

  - stage: dev
    displayName: 'Development'
    variables:
      img_url: 'gcr.io/gcp-cf-272812/go-microservice:$(Build.SourceVersion)'

    jobs:
      - template: 'templates/helm-deployment.yml'
        parameters:
          environment: 'dev.default'
          kube_connection_type: 'Kubernetes Service Connection'
          kube_service_connection: 'dev-default-1589456418781'
          helm_chart_archive_path: '$(Agent.BuildDirectory)/helm/go-microservice-0.1.0.tgz'
          helm_values_file_path: '$(Agent.BuildDirectory)/helm/go-microservice-0.1.0'
          helm_override_values: 'blue.image=$(img_url),green.image=$(img_url)'
          helm_release_name: 'go-microservice-dev'
         
  - stage: qa
    displayName: 'QA'
    variables:
      img_url: 'gcr.io/gcp-cf-272812/go-microservice:$(Build.SourceVersion)'

    jobs:
      - template: 'templates/helm-deployment.yml'
        parameters:
          environment: 'qa.qa'
          kube_connection_type: 'Kubernetes Service Connection'
          kube_service_connection: 'dev-default-1589456418781'
          helm_chart_archive_path: '$(Agent.BuildDirectory)/helm/go-microservice-0.1.0.tgz'
          helm_values_file_path: '$(Agent.BuildDirectory)/helm/go-microservice-0.1.0'
          helm_override_values: 'blue.image=$(img_url),green.image=$(img_url)'
          helm_release_name: 'go-microservice-qa'
