# Starter pipeline

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build
    displayName: 'Build'

    jobs:

      - job: build
        displayName: 'Build'
        steps:

        - task: Docker@2
          inputs:
            containerRegistry: 'gcrServiceConnection'
            repository: 'gcp-cf-272812/go-microservice'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.SourceVersion)'

  - stage: dev
    displayName: 'Development'

    jobs:

      - job: package
        displayName: "Helm Package"
        steps:

        - task: HelmDeploy@0
          inputs:
            command: 'package'
            chartPath: './chart'
            destination: $(Build.ArtifactStagingDirectory)
            save: false

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)/go-microservice-0.1.0.tgz'
            artifactName: helm-package

      - deployment: deploy
        dependsOn: package
        displayName: 'Deploy Helm Chart'
        environment: dev.default
        variables:
          img_url: 'gcr.io/gcp-cf-272812/go-microservice:$(Build.SourceVersion)'

        strategy:
          runOnce:
            deploy:
              steps:

                - task: HelmDeploy@0
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: 'dev-default-1589456418781'
                    namespace: $(k8sNamespace)
                    command: 'install'
                    overrideValues: blue.image=$(img_url),green.image=$(img_url)
                    chartType: 'FilePath'
                    chartPath: $(Agent.BuildDirectory)/go-microservice-0.1.0.tgz
                    chartName: 'go-microservice'
