# Starter pipeline

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build
    displayName: 'Build'

    jobs:

      - job: build
        displayName: 'Build'
        steps:

        - task: Docker@2
          inputs:
            command: 'build'
            Dockerfile: '**/Dockerfile'

  - stage: dev
    displayName: 'Development'

    jobs:

      - deployment: deploy
        displayName: 'Deploy Helm Chart'

        environment: dev.default

        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmDeploy@0
                  inputs:
                    namespace: $(k8sNamespace)
                    command: 'ls'

                - task: Kubernetes@1
                  inputs:
                    namespace: $(k8sNamespace)
                    command: 'get'
                    arguments: 'namespaces'







