# Starter pipeline

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: build
    displayName: 'Build'

    jobs:

      - job: build
        displayName: 'Build'
        steps:

        - script: echo ls

        - task: Docker@2
          inputs:
            command: 'build'
            Dockerfile: '**/Dockerfile'
            tags: $(Build.SourceVersion)

  - stage: dev
    displayName: 'Development'

    jobs:

      - deployment: deploy
        displayName: 'Deploy Helm Chart'

        environment: dev.default

        strategy:
          runOnce:
            deploy:
              steps:

                - script: ls
                # - task: HelmDeploy@0
                #   inputs:
                #     connectionType: 'Kubernetes Service Connection'
                #     kubernetesServiceConnection: 'dev-default-1589456418781'
                #     namespace: $(k8sNamespace)
                #     command: 'install'
                #     overrideValues: blue.image=$(Build.SourceVersion),blue.pullPolicy=IfNotPresent,green.image=$(Build.SourceVersion),green.pullPolicy=IfNotPresent
                #     chartType: 'FilePath'
                #     chartPath: 'chart/'
                #     chartName: 'go-microservice'

                # - task: Kubernetes@1
                #   inputs:

                #     namespace: $(k8sNamespace)
                #     command: 'get'
                #     arguments: 'namespaces'
