apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice-green
spec:
  replicas: {{ .Values.green.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: go-microservice
      app.kubernetes.io/instance: {{ .Release.Name }}
      slot: green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-microservice
        app.kubernetes.io/instance: {{ .Release.Name }}
        slot: green
    spec:
      containers:
        - name: go-microservice
          image: "{{ .Values.green.image }}"
          imagePullPolicy: {{ .Values.green.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
          readinessProbe:
            httpGet:
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi