apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: go-microservice
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: go-microservice
          servicePort: 8080
