parameters:
  - name: environment
    type: string
    default: ''

  - name: helm_chart_archive_path
    type: string
    default: ''

  - name: helm_values_file_path
    type: string
    default: ''

  - name: kube_connection_type
    type: string
    default: ''

  - name: kube_service_connection
    type: string
    default: ''

  - name: helm_override_values
    type: object
    default: ''

  - name: helm_release_name
    type: string
    default: ''

jobs:

  - deployment: deploy
    displayName: 'Deploy Helm Chart'
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:

          - task: ExtractFiles@1
            displayName: 'Get Environment overrides'
            inputs:
              archiveFilePatterns: ${{ parameters.helm_chart_archive_path }}
              destinationFolder: ${{ parameters.helm_values_file_path }}
              cleanDestinationFolder: true

          - task: HelmDeploy@0
            displayName: 'Deploy Helm chart to environment'
            inputs:
              connectionType: ${{ parameters.kube_connection_type }}
              kubernetesServiceConnection: ${{ parameters.kube_service_connection }}
              namespace: $(Environment.ResourceName)
              command: 'upgrade'
              valueFile: ${{ parameters.helm_values_file_path }}/go-microservice/$(Environment.Name).yaml
              overrideValues: ${{ parameters.helm_override_values }}
              chartType: 'FilePath'
              chartPath: ${{ parameters.helm_chart_archive_path }}
              releaseName: ${{ parameters.helm_release_name }}
